### PR TITLE
Add some of the features and functions that are currently missing.

### PR DESCRIPTION
**Pull request by bryanjjohnson**

### CODE REVIEW

**Comment by danzel** [comment]
If you fix the whitespace I'll accept this.
As mentioned in #1 this repository is going to be deprecated in favor of https://github.com/dobrud/typed-mapbox-gl however.

**Comment by bryanjjohnson** [comment]
Some of the things I added I noticed are not in either repository. What is your preferred style for whitespace.

**Comment by bryanjjohnson** [comment]
I think I fixed a lot of the whitespace

**Comment by danzel** [comment]
Awesome, whitespace looks better!

**Pull request merged**
